FROM ubuntu:latest
RUN apt-get update && apt-get -y upgrade && apt-get -y install python3-pip build-essential
WORKDIR /usr/src/app
RUN pip3 install torch torchvision --index-url https://download.pytorch.org/whl/cpu
COPY requirements.txt requirements-dev.txt joey/
RUN pip3 install -r joey/requirements-dev.txt
COPY . joey/
RUN pip3 install -e joey
WORKDIR /usr/src/app/joey
